<?xml version="1.0" encoding="utf-8"?>
<xsl:stylesheet version="3.0" xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
                xmlns:atom="http://www.w3.org/2005/Atom" xmlns:dc="http://purl.org/dc/elements/1.1/"
                xmlns:itunes="http://www.itunes.com/dtds/podcast-1.0.dtd"
>
  <xsl:output method="html" version="1.0" encoding="UTF-8" indent="yes"/>
  <xsl:template match="/">
    <html xmlns="http://www.w3.org/1999/xhtml">
      <head>
        <title><xsl:value-of select="/rss/channel/title"/> Feed</title>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
        <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1"/>
        <style type="text/css">
body {
  text-rendering:optimizeLegibility;-webkit-font-smoothing:antialiased;-moz-osx-font-smoothing:grayscale;margin:0;color:rgba(0,0,0,.86);font:16px/1.42 -apple-system,BlinkMacSystemFont,Helvetica Neue,PingFang SC,Hiragino Sans GB,Droid Sans Fallback,Microsoft YaHei,sans-serif
}
img {
  max-width:100%
}
.inner {
  max-width:860px;margin:0 auto;padding:0 20px;box-sizing:border-box
}
.top {
  margin-top:10px;font-size:12px
}
.top,.top a {
  color:#9ea0a6
}
.head {
  padding-top:80px;padding-bottom:40px
}
.head_logo {
  float:left;width:120px;height:120px;margin-right:20px
}
.head_main {
  overflow:hidden
}
.head h1 {
  font-size:36px;font-weight:400;margin:0;color:#000
}
.head p {
  margin:0 0 10px;font-size:18px;font-weight:300;color:#9ea0a6
}
.head .head_link {
  font-size:14px;font-weight:600;color:#333;text-decoration:none
}
.links {
  margin:30px auto
}
.links a {
  display:inline-block;text-decoration:none;line-height:28px;padding-left:30px;background-position:0;background-size:24px 24px;background-repeat:no-repeat;font-weight:600;color:#333
}
.links a+a {
  margin-left:1.4em
}
.links a.podcast:hover {
  color:#93c
}
.links a.castro:hover {
  color:#00b265
}
.links a.google:hover {
  color:#4285f4
}
.links a.spotify:hover {
  color:#1ed760
}
.links a.overcast:hover {
  color:#fc7e0f
}
.item {
  border-top:1px solid rgba(0,0,0,.04);padding:20px;margin:20px auto
}
.item_meta {
  font-size:14px;color:#9ea0a6
}
.item a {
  color:rgba(0,0,0,.98);text-decoration:none
}
.item>h2 {
  margin:0
}
.item>h3 {
  margin:6px 0 10px;font-size:18px;font-weight:300;color:#9ea0a6
}
.item>audio {
  display:block;width:100%;margin-top:20px
}
.typlog-foot {
  border-top:1px solid rgba(0,0,0,.04);padding:10px 20px
}
.typlog-foot .title {
  text-decoration:none;text-transform:uppercase;font-size:16px;font-weight:900;color:rgba(0,0,0,.2);letter-spacing:.02em;margin-right:1em
}
.typlog-foot nav {
  display:inline-block
}
.typlog-foot nav>a {
  text-decoration:none;color:rgba(0,0,0,.6);-webkit-transition:color .2s ease;transition:color .2s ease;font-size:.92em
}
.typlog-foot nav>a+a:before {
  content:" / ";font-size:10px;color:rgba(0,0,0,.1)
}
</style>
      </head>
      <body>
        <xsl:if test="/rss/channel/itunes:image">
          <div class="top inner">
            This is a Podcast RSS Feed generated by <a href="https://typlog.com/" target="_blank">Typlog</a>.
            Podcast apps can use the URL in the address bar. Find out
            <a href="https://blog.typlog.com/subscribe-podcast-feed" target="_blank">
              how to subscribe a podcast via feed</a>.
          </div>
        </xsl:if>
        <xsl:if test="/rss/channel/item/dc:creator">
          <div class="top inner">
            This is a RSS Feed generated by <a href="https://typlog.com/" target="_blank">Typlog</a>.
            RSS readers can use the URL in the address bar.
          </div>
        </xsl:if>
        <div class="head inner">
          <xsl:if test="/rss/channel/image">
            <a class="head_logo">
              <xsl:attribute name="href">
                <xsl:value-of select="/rss/channel/link"/>
              </xsl:attribute>
              <img>
                <xsl:attribute name="src">
                  <xsl:value-of select="/rss/channel/image/url"/>
                </xsl:attribute>
                <xsl:attribute name="title">
                  <xsl:value-of select="/rss/channel/title"/>
                </xsl:attribute>
              </img>
            </a>
          </xsl:if>
          <div class="head_main">
            <h1><xsl:value-of select="/rss/channel/title"/></h1>
            <p><xsl:value-of select="/rss/channel/description"/></p>
            <a class="head_link" target="_blank">
              <xsl:attribute name="href">
                <xsl:value-of select="/rss/channel/link"/>
              </xsl:attribute>
              Visit Website &#x2192;
            </a>
          </div>
        </div>
        <xsl:if test="/rss/channel/atom:link[@rel='alternate']">
          <div class="links inner">
            <xsl:for-each select="/rss/channel/atom:link[@rel='alternate']">
              <a target="_blank">
                <xsl:attribute name="class">
                  <xsl:value-of select="@icon"/>
                </xsl:attribute>
                <xsl:attribute name="href">
                  <xsl:value-of select="@href"/>
                </xsl:attribute>
                <xsl:value-of select="@title"/>
              </a>
            </xsl:for-each>
          </div>
        </xsl:if>
        <xsl:for-each select="/rss/channel/item">
          <div class="item inner">
            <div class="item_meta">
              <span><xsl:value-of select="pubDate" /></span>
              <xsl:if test="itunes:duration">
                &#x02022;
                <span><xsl:value-of select="itunes:duration" /></span>
              </xsl:if>
            </div>
            <h2>
              <a target="_blank">
                <xsl:attribute name="href">
                  <xsl:value-of select="link"/>
                </xsl:attribute>
                <xsl:value-of select="title"/>
              </a>
            </h2>
            <xsl:if test="itunes:subtitle">
              <h3><xsl:value-of select="itunes:subtitle" /></h3>
            </xsl:if>
            <xsl:if test="itunes:duration">
              <audio controls="true" preload="none">
                <xsl:attribute name="src">
                  <xsl:value-of select="enclosure/@url"/>
                </xsl:attribute>
              </audio>
            </xsl:if>
          </div>
        </xsl:for-each>
        <div class="typlog-foot">
          <a class="title" href="https://typlog.com/?utm_medium=feed">Typlog</a>
          <nav>
            <a href="https://typlog.com/about?utm_medium=feed">About</a>
            <a href="https://typlog.com/terms?utm_medium=feed">Terms</a>
          </nav>
        </div>
      </body>
    </html>
  </xsl:template>
</xsl:stylesheet>